import { Equipment } from '../types';

export const defaultEquipment: Equipment[] = [
  {
    id: 'eq-001',
    name: 'Canon EOS R6 Camera',
    category: 'Media',
    location: 'Media Room, Level 4',
    condition: 'Excellent',
    status: 'Available',
    image: '/camera.jpg',
  },
  {
    id: 'eq-002',
    name: 'Epson Pro EX9220 Projector',
    category: 'Presentation',
    location: 'IT Helpdesk, Level 2',
    condition: 'Good',
    status: 'Available',
    image: '/projector.jpg',
  },
  {
    id: 'eq-003',
    name: 'Sony A7III Camera',
    category: 'Media',
    location: 'Media Room, Level 4',
    condition: 'Good',
    status: 'Available',
    image: '/camera2.jpg',
  },
  {
    id: 'eq-004',
    name: 'Manfrotto Element Tripod',
    category: 'Accessories',
    location: 'Media Room, Level 4',
    condition: 'Fair',
    status: 'Available',
    image: '/tripod.jpg',
  },
  {
    id: 'eq-005',
    name: 'Rode Wireless GO II',
    category: 'Audio',
    location: 'Media Room, Level 4',
    condition: 'Excellent',
    status: 'Available',
    image: '/mic.jpg',
  },
  {
    id: 'eq-006',
    name: '10m HDMI Cable',
    category: 'Accessories',
    location: 'IT Helpdesk, Level 2',
    condition: 'Good',
    status: 'Available',
    image: '/hdmi.jpg',
  },
  {
    id: 'eq-007',
    name: 'Heavy Duty Extension Cord',
    category: 'Accessories',
    location: 'Events Storage, Level 1',
    condition: 'Fair',
    status: 'Available',
    image: '/cord.jpg',
  },
  {
    id: 'eq-008',
    name: 'Logitech R400 Presentation Clicker',
    category: 'Presentation',
    location: 'IT Helpdesk, Level 2',
    condition: 'Excellent',
    status: 'Available',
    image: '/clicker.jpg',
  },
  {
    id: 'eq-009',
    name: 'JBL PartyBox Portable Speaker',
    category: 'Audio',
    location: 'Events Storage, Level 1',
    condition: 'Good',
    status: 'Available',
    image: '/speaker.jpg',
  },
  {
    id: 'eq-010',
    name: 'Dell XPS 15 Lab Laptop',
    category: 'Computing',
    location: 'IT Helpdesk, Level 2',
    condition: 'Good',
    status: 'Available',
    image: '/laptop.jpg',
  },
  {
    id: 'eq-011',
    name: 'Anker USB-C Hub Adapter',
    category: 'Computing',
    location: 'IT Helpdesk, Level 2',
    condition: 'Excellent',
    status: 'Available',
    image: '/hub.jpg',
  },
  {
    id: 'eq-012',
    name: 'Neewer 18" Ring Light',
    category: 'Media',
    location: 'Media Room, Level 4',
    condition: 'Good',
    status: 'Available',
    image: '/ringlight.jpg',
  }
];
